/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContentMetadata = IDL.Record({
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'studioType' : IDL.Text,
  'isPublic' : IDL.Bool,
});
export const Time = IDL.Int;
export const DesignRecord = IDL.Record({
  'id' : IDL.Text,
  'metadata' : ContentMetadata,
  'creationDate' : Time,
  'image' : IDL.Vec(IDL.Nat8),
});
export const SubscriptionTier = IDL.Variant({
  'big' : IDL.Null,
  'premium' : IDL.Null,
  'none' : IDL.Null,
  'extreme' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'credits' : IDL.Nat,
  'username' : IDL.Text,
  'apiKeys' : IDL.Vec(IDL.Text),
  'subscriptionTier' : SubscriptionTier,
  'teamMembers' : IDL.Vec(IDL.Principal),
  'subscriptionActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCredits' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'balance' : IDL.Func([], [IDL.Nat], ['query']),
  'createUserProfile' : IDL.Func([IDL.Text], [], []),
  'decrementCredits' : IDL.Func([IDL.Nat], [], []),
  'generateApiKey' : IDL.Func([], [IDL.Text], []),
  'getAllPublicDesigns' : IDL.Func([], [IDL.Vec(DesignRecord)], ['query']),
  'getAllPublicDesignsByTitle' : IDL.Func(
      [],
      [IDL.Vec(DesignRecord)],
      ['query'],
    ),
  'getAllUserDesigns' : IDL.Func([], [IDL.Vec(DesignRecord)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getApiKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDesign' : IDL.Func([IDL.Text], [IDL.Opt(DesignRecord)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserDesigns' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DesignRecord)],
      ['query'],
    ),
  'inviteTeamMember' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscriptionActive' : IDL.Func([], [IDL.Bool], ['query']),
  'removeTeamMember' : IDL.Func([IDL.Principal], [], []),
  'saveDesign' : IDL.Func([DesignRecord], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'setDesignPublicStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setSubscriptionStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'setSubscriptionTier' : IDL.Func([IDL.Principal, SubscriptionTier], [], []),
  'subscriptionTier' : IDL.Func([], [SubscriptionTier], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContentMetadata = IDL.Record({
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'studioType' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  const Time = IDL.Int;
  const DesignRecord = IDL.Record({
    'id' : IDL.Text,
    'metadata' : ContentMetadata,
    'creationDate' : Time,
    'image' : IDL.Vec(IDL.Nat8),
  });
  const SubscriptionTier = IDL.Variant({
    'big' : IDL.Null,
    'premium' : IDL.Null,
    'none' : IDL.Null,
    'extreme' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'credits' : IDL.Nat,
    'username' : IDL.Text,
    'apiKeys' : IDL.Vec(IDL.Text),
    'subscriptionTier' : SubscriptionTier,
    'teamMembers' : IDL.Vec(IDL.Principal),
    'subscriptionActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCredits' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'balance' : IDL.Func([], [IDL.Nat], ['query']),
    'createUserProfile' : IDL.Func([IDL.Text], [], []),
    'decrementCredits' : IDL.Func([IDL.Nat], [], []),
    'generateApiKey' : IDL.Func([], [IDL.Text], []),
    'getAllPublicDesigns' : IDL.Func([], [IDL.Vec(DesignRecord)], ['query']),
    'getAllPublicDesignsByTitle' : IDL.Func(
        [],
        [IDL.Vec(DesignRecord)],
        ['query'],
      ),
    'getAllUserDesigns' : IDL.Func([], [IDL.Vec(DesignRecord)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getApiKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDesign' : IDL.Func([IDL.Text], [IDL.Opt(DesignRecord)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserDesigns' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DesignRecord)],
        ['query'],
      ),
    'inviteTeamMember' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscriptionActive' : IDL.Func([], [IDL.Bool], ['query']),
    'removeTeamMember' : IDL.Func([IDL.Principal], [], []),
    'saveDesign' : IDL.Func([DesignRecord], [], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'setDesignPublicStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setSubscriptionStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'setSubscriptionTier' : IDL.Func([IDL.Principal, SubscriptionTier], [], []),
    'subscriptionTier' : IDL.Func([], [SubscriptionTier], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };