/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DesignRecord {
    id: string;
    metadata: ContentMetadata;
    creationDate: Time;
    image: Uint8Array;
}
export interface ContentMetadata {
    title: string;
    createdBy: Principal;
    studioType: string;
    isPublic: boolean;
}
export type Time = bigint;
export interface UserProfile {
    principal: Principal;
    credits: bigint;
    username: string;
    apiKeys: Array<string>;
    subscriptionTier: SubscriptionTier;
    teamMembers: Array<Principal>;
    subscriptionActive: boolean;
}
export enum SubscriptionTier {
    big = "big",
    premium = "premium",
    none = "none",
    extreme = "extreme",
    small = "small",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
/**
 * / * CREATEai by angieCREATEs — Backend Canister
 * /  * ============================================
 * /  *
 * /  * This is the single-actor backend for the CREATEai platform, an all-in-one
 * /  * AI-powered fashion design platform. It runs on the Internet Computer using
 * /  * enhanced orthogonal persistence — all state survives upgrades automatically
 * /  * without `stable` keywords or pre/post-upgrade hooks.
 * /  *
 * /  * ## Architecture
 * /  *
 * /  * The actor owns all persistent state (Maps) and exposes a flat public API
 * /  * grouped into the following domains:
 * /  *
 * /  * ### Access Control
 * /  *   - _initializeAccessControlWithSecret  — Bootstrap the first admin via a secret token
 * /  *   - getCallerUserRole                   — Query the caller's assigned role
 * /  *   - assignCallerUserRole                — Admin-only: assign a role to any principal
 * /  *   - isCallerAdmin                       — Check whether the caller holds the admin role
 * /  *
 * /  * ### User Profile Management
 * /  *   - createUserProfile                   — Register a new user profile (username required)
 * /  *   - getCallerUserProfile                — Fetch the caller's own profile
 * /  *   - saveUserProfile                     — Overwrite the caller's own profile record
 * /  *   - getAllUserProfiles                   — Admin-only: list every registered profile
 * /  *
 * /  * ### Credits & Subscriptions
 * /  *   - balance                             — Query the caller's current credit balance
 * /  *   - addCredits                          — Admin-only: add credits to any user's account
 * /  *   - decrementCredits                    — Deduct credits from the caller's account
 * /  *   - isSubscriptionActive                — Check whether the caller's subscription is active
 * /  *   - subscriptionTier                    — Query the caller's subscription tier
 * /  *   - setSubscriptionTier                 — Admin-only: set a user's subscription tier
 * /  *   - setSubscriptionStatus               — Admin-only: activate or deactivate a subscription
 * /  *
 * /  * ### API Keys
 * /  *   - generateApiKey                      — Generate a new API key for the caller
 * /  *   - getApiKeys                          — List all API keys belonging to the caller
 * /  *
 * /  * ### Design Management
 * /  *   - saveDesign                          — Persist a new design record owned by the caller
 * /  *   - getDesign                           — Fetch a design by ID (own or public designs only)
 * /  *   - getAllUserDesigns                    — List every design created by the caller
 * /  *   - getUserDesigns                      — List designs for any principal (public + own + admin)
 * /  *   - setDesignPublicStatus               — Toggle public visibility of a caller-owned design
 * /  *   - getAllPublicDesigns                  — List all publicly visible designs
 * /  *   - getAllPublicDesignsByTitle           — Same as above, sorted alphabetically by title
 * /  *
 * /  * ### Team Collaboration
 * /  *   - inviteTeamMember                    — Add a principal to the caller's team
 * /  *   - removeTeamMember                    — Remove a principal from the caller's team
 * /  *   - getTeamMembers                      — List all team members on the caller's account
 * /  *
 * /  * ## Authorization Model
 * /  *
 * /  * Three roles exist: #admin > #user > #guest
 * /  *   - #guest  — anonymous principals; read-only access to public content
 * /  *   - #user   — authenticated principals who have called _initializeAccessControlWithSecret
 * /  *   - #admin  — the first principal to bootstrap with the correct CAFFEINE_ADMIN_TOKEN
 * /  *
 * /  * Admins pass all permission checks for any required role.
 */
export interface backendInterface {
    /**
     * / * Registers the caller and assigns their role (admin or user).
     * /    *
     * /    * This is the sole entry point for role assignment. It must be called once
     * /    * per principal before any other protected endpoint is used.
     * /    *
     * /    * Admin bootstrap: the first authenticated caller to supply the correct
     * /    * CAFFEINE_ADMIN_TOKEN environment variable is granted #admin. All subsequent
     * /    * callers — including those who supply the correct token again — receive #user.
     * /    *
     * /    * The CAFFEINE_ADMIN_TOKEN is read from the canister environment at call time
     * /    * and is never stored in canister state, preventing leakage.
     * /    *
     * /    * @param userSecret — Token supplied by the caller. Matching the env token grants admin.
     * /    * @throws If CAFFEINE_ADMIN_TOKEN is not set in the canister environment.
     */
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / * Adds the specified number of credits to a user's account. Admin-only.
     * /    *
     * /    * Called by the payment flow after a successful Stripe checkout or manual
     * /    * credit allocation. The new balance is returned so the admin UI can display
     * /    * an immediate confirmation.
     * /    *
     * /    * Input validation:
     * /    *   - `amount` must be greater than zero (Nat is always non-negative, but
     * /    *     adding 0 credits would be a no-op and likely indicates a client bug).
     * /    *
     * /    * @param user   — The principal whose account will be credited.
     * /    * @param amount — Number of credits to add. Must be greater than 0.
     * /    * @returns Nat  — The user's updated credit balance after the addition.
     * /    * @throws If the caller is not an administrator.
     * /    * @throws If no profile exists for `user`.
     * /    * @throws If `amount` is 0.
     * /    * @sideEffect Updates the `credits` field in `userProfiles` for `user`.
     */
    addCredits(user: Principal, amount: bigint): Promise<bigint>;
    /**
     * / * Assigns the specified role to any principal. Admin-only.
     * /    *
     * /    * Can be used to promote a user to admin, demote an admin, or revoke access.
     * /    * Overwrites any existing role for the target principal.
     * /    *
     * /    * @param user — The principal whose role will be updated.
     * /    * @param role — The new role to assign (#admin | #user | #guest).
     * /    * @throws If the caller is not an admin.
     */
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / * Returns the caller's current credit balance.
     * /    *
     * /    * This is a query (free, read-only). Credits are consumed by AI studio
     * /    * operations via decrementCredits and replenished by addCredits (admin).
     * /    *
     * /    * @returns Nat — Number of credits available to the caller.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     */
    balance(): Promise<bigint>;
    /**
     * / * Creates a new user profile for the caller.
     * /    *
     * /    * Registers the caller with a blank credit balance, no subscription, an empty
     * /    * team, and no API keys. Calling this function twice for the same principal
     * /    * is an error — profiles cannot be recreated once established.
     * /    *
     * /    * Input validation:
     * /    *   - `username` must not be empty.
     * /    *
     * /    * @param username — The display name to register. Must be a non-empty string.
     * /    * @throws If the caller already has a profile.
     * /    * @throws If `username` is an empty string.
     * /    * @sideEffect Inserts a new entry into `userProfiles`.
     */
    createUserProfile(username: string): Promise<void>;
    /**
     * / * Deducts `credits` from the caller's balance.
     * /    *
     * /    * Called by each AI studio operation after generating output. The decrement
     * /    * is atomic — either the full amount is deducted or the call traps with no
     * /    * state change.
     * /    *
     * /    * Input validation:
     * /    *   - `credits` must be greater than zero.
     * /    *   - The caller's current balance must be >= `credits`.
     * /    *
     * /    * @param credits — Number of credits to deduct. Must be > 0.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If `credits` is 0.
     * /    * @throws If the caller has insufficient credits.
     * /    * @throws If no profile exists for the caller.
     * /    * @sideEffect Reduces the `credits` field in the caller's profile.
     */
    decrementCredits(credits: bigint): Promise<void>;
    /**
     * / * Generates a new API key and appends it to the caller's key list.
     * /    *
     * /    * Keys are sequentially numbered using the current key-list length as a suffix
     * /    * (e.g. "api-key-0", "api-key-1"). This keeps key generation deterministic and
     * /    * free of external randomness. Callers can revoke keys by saving a filtered
     * /    * profile via saveUserProfile.
     * /    *
     * /    * Note: keys are currently opaque identifiers. For production use, consider
     * /    * adding a hashing layer so the raw key is never stored in canister state.
     * /    *
     * /    * @returns Text — The newly generated API key string.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     * /    * @sideEffect Appends a new key to the `apiKeys` array in the caller's profile.
     */
    generateApiKey(): Promise<string>;
    /**
     * / * Returns all designs that are publicly visible, in storage order (unordered).
     * /    *
     * /    * Used to populate the community gallery homepage. For a sorted listing,
     * /    * use getAllPublicDesignsByTitle.
     * /    *
     * /    * @returns [DesignRecord] — All designs where metadata.isPublic == true.
     */
    getAllPublicDesigns(): Promise<Array<DesignRecord>>;
    /**
     * / * Returns all publicly visible designs sorted alphabetically by title.
     * /    *
     * /    * Identical to getAllPublicDesigns but with a deterministic sort order using
     * /    * DesignRecord.compareByTitle. Useful for paginated gallery views where
     * /    * consistent ordering matters.
     * /    *
     * /    * @returns [DesignRecord] — Public designs sorted A→Z by metadata.title.
     */
    getAllPublicDesignsByTitle(): Promise<Array<DesignRecord>>;
    /**
     * / * Returns every design created by the caller.
     * /    *
     * /    * Includes both public and private designs. The returned list is unordered.
     * /    * Use getAllPublicDesignsByTitle for a sorted community view.
     * /    *
     * /    * @returns [DesignRecord] — All designs where metadata.createdBy == caller.
     * /    * @throws If the caller does not have the #user role or higher.
     */
    getAllUserDesigns(): Promise<Array<DesignRecord>>;
    /**
     * / * Returns every registered user profile. Admin-only.
     * /    *
     * /    * Intended for admin dashboards and analytics. The order of profiles in the
     * /    * returned array is not guaranteed.
     * /    *
     * /    * @returns [UserProfile] — All profiles stored in the canister.
     * /    * @throws If the caller is not an administrator.
     */
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    /**
     * / * Returns all API keys belonging to the caller.
     * /    *
     * /    * This is a query (free, read-only). Use the returned keys to authenticate
     * /    * server-to-server calls against the CREATEai REST API.
     * /    *
     * /    * @returns [Text] — All API keys currently assigned to the caller.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     */
    getApiKeys(): Promise<Array<string>>;
    /**
     * / * Returns the full profile record for the caller.
     * /    *
     * /    * This is a query (read-only, free) — no state changes occur.
     * /    *
     * /    * @returns UserProfile — The caller's complete profile.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     */
    getCallerUserProfile(): Promise<UserProfile>;
    /**
     * / * Returns the role currently assigned to the caller.
     * /    *
     * /    * Useful for clients to determine which UI features to enable.
     * /    *
     * /    * @returns UserRole — #admin | #user | #guest
     * /    * @throws If the caller is authenticated but has not yet called _initializeAccessControlWithSecret.
     */
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / * Fetches a single design by its unique ID.
     * /    *
     * /    * Access rules (enforced server-side):
     * /    *   - The caller may always retrieve their own designs.
     * /    *   - Any principal (including guests) may retrieve publicly visible designs.
     * /    *   - Private designs belonging to another user return null (not a trap) to
     * /    *     avoid leaking the existence of the design.
     * /    *
     * /    * @param id       — The unique design identifier to look up.
     * /    * @returns ?DesignRecord — The design record if accessible, or null if not found
     * /    *                          or not permitted.
     */
    getDesign(id: string): Promise<DesignRecord | null>;
    /**
     * / * Returns all principals currently on the caller's team.
     * /    *
     * /    * This is a query (free, read-only). The returned array preserves insertion
     * /    * order (most recently added member is last).
     * /    *
     * /    * @returns [Principal] — The caller's current team members.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     */
    getTeamMembers(): Promise<Array<Principal>>;
    /**
     * / * Returns designs belonging to any specified principal, with visibility rules.
     * /    *
     * /    * Visibility rules for the returned set:
     * /    *   - Public designs belonging to `id` are always included.
     * /    *   - Private designs belonging to `id` are included only if
     * /    *     `id == caller` (viewing your own) or the caller is an admin.
     * /    *
     * /    * @param id       — The principal whose designs to fetch.
     * /    * @returns [DesignRecord] — Filtered design records according to the visibility rules above.
     * /    * @throws If the caller does not have the #user role or higher.
     */
    getUserDesigns(id: Principal): Promise<Array<DesignRecord>>;
    /**
     * / * Adds a principal to the caller's team member list.
     * /    *
     * /    * Team members are stored on the inviting user's profile. Duplicate invites
     * /    * are not checked — callers are responsible for checking getTeamMembers before
     * /    * adding to avoid duplicates.
     * /    *
     * /    * @param newMember — The principal to add to the caller's team.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     * /    * @sideEffect Appends `newMember` to the caller's `teamMembers` array.
     */
    inviteTeamMember(newMember: Principal): Promise<void>;
    /**
     * / * Returns true if the caller currently holds the #admin role.
     * /    *
     * /    * A convenience query; equivalent to checking getCallerUserRole() == #admin.
     * /    *
     * /    * @returns Bool — true if the caller is an admin, false otherwise.
     */
    isCallerAdmin(): Promise<boolean>;
    /**
     * / * Returns whether the caller's subscription is currently active.
     * /    *
     * /    * A subscription being active means the periodic payment is up-to-date.
     * /    * An active subscription may still be tier #none if it was just created;
     * /    * always check subscriptionTier for access-level decisions.
     * /    *
     * /    * @returns Bool — true if the caller's subscription is active.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     */
    isSubscriptionActive(): Promise<boolean>;
    /**
     * / * Removes a principal from the caller's team member list.
     * /    *
     * /    * If the specified principal is not currently a team member, the call
     * /    * succeeds silently (idempotent removal).
     * /    *
     * /    * @param member — The principal to remove from the caller's team.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     * /    * @sideEffect Filters `member` out of the caller's `teamMembers` array.
     */
    removeTeamMember(member: Principal): Promise<void>;
    /**
     * / * Persists a new AI-generated design record owned by the caller.
     * /    *
     * /    * The caller must be listed as the design's creator (`metadata.createdBy`)
     * /    * — the backend enforces this to prevent one user from creating designs
     * /    * attributed to another user's account.
     * /    *
     * /    * Input validation:
     * /    *   - `historyEntry.id` must be non-empty.
     * /    *   - `historyEntry.metadata.title` must be non-empty.
     * /    *   - `historyEntry.metadata.createdBy` must equal `caller`.
     * /    *
     * /    * @param historyEntry — The complete design record to store.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If the design ID is empty.
     * /    * @throws If the design title is empty.
     * /    * @throws If `historyEntry.metadata.createdBy` does not match the caller.
     * /    * @sideEffect Inserts or overwrites the design entry in `designs`.
     */
    saveDesign(historyEntry: DesignRecord): Promise<void>;
    /**
     * / * Overwrites the caller's profile with the provided record.
     * /    *
     * /    * The caller may only save their own profile (the stored principal must match
     * /    * the caller's identity). This function is used to persist profile edits made
     * /    * in the user dashboard.
     * /    *
     * /    * Note: The entire profile record is replaced atomically. Partial updates are
     * /    * not supported — callers should read, modify, then write back.
     * /    *
     * /    * @param profile — The updated profile record to persist.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @sideEffect Replaces the existing profile in `userProfiles`.
     */
    saveUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / * Sets the public/private visibility flag on a design owned by the caller.
     * /    *
     * /    * Only the creator of a design can toggle its visibility. Marking a design
     * /    * public will expose it in the community gallery accessible to all users.
     * /    *
     * /    * @param id       — The unique ID of the design to update.
     * /    * @param isPublic — true to publish to the community gallery; false to make private.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no design exists with the given `id`.
     * /    * @throws If the caller is not the creator of the design.
     * /    * @sideEffect Updates the `metadata.isPublic` field of the design in `designs`.
     */
    setDesignPublicStatus(id: string, isPublic: boolean): Promise<void>;
    /**
     * / * Activates or deactivates a user's subscription. Admin-only.
     * /    *
     * /    * Called by the Stripe webhook handler on subscription payment success,
     * /    * failure, cancellation, or manual override. Setting `active = false` while
     * /    * the tier remains set allows graceful degradation (tier shows but features
     * /    * are locked until payment resumes).
     * /    *
     * /    * @param user   — The principal whose subscription status will change.
     * /    * @param active — true to activate, false to deactivate.
     * /    * @throws If the caller is not an administrator.
     * /    * @throws If no profile exists for `user`.
     * /    * @sideEffect Updates the `subscriptionActive` field in `userProfiles` for `user`.
     */
    setSubscriptionStatus(user: Principal, active: boolean): Promise<void>;
    /**
     * / * Updates a user's subscription tier. Admin-only.
     * /    *
     * /    * Called by the Stripe webhook handler after a successful subscription
     * /    * upgrade or downgrade. Does NOT automatically set `subscriptionActive` —
     * /    * that must be set separately via setSubscriptionStatus.
     * /    *
     * /    * @param user — The principal whose tier will be changed.
     * /    * @param tier — The new subscription tier to assign.
     * /    * @throws If the caller is not an administrator.
     * /    * @throws If no profile exists for `user`.
     * /    * @sideEffect Updates the `subscriptionTier` field in `userProfiles` for `user`.
     */
    setSubscriptionTier(user: Principal, tier: SubscriptionTier): Promise<void>;
    /**
     * / * Returns the caller's current subscription tier.
     * /    *
     * /    * Use this to determine which feature set the caller has access to.
     * /    * Tier hierarchy (ascending): #none < #small < #medium < #big < #premium < #extreme
     * /    *
     * /    * @returns SubscriptionTier — The caller's active tier.
     * /    * @throws If the caller does not have the #user role or higher.
     * /    * @throws If no profile exists for the caller.
     */
    subscriptionTier(): Promise<SubscriptionTier>;
}
import type { DesignRecord as _DesignRecord, SubscriptionTier as _SubscriptionTier, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCredits(arg0: Principal, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCredits(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCredits(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async balance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.balance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.balance();
            return result;
        }
    }
    async createUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0);
            return result;
        }
    }
    async decrementCredits(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.decrementCredits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.decrementCredits(arg0);
            return result;
        }
    }
    async generateApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateApiKey();
            return result;
        }
    }
    async getAllPublicDesigns(): Promise<Array<DesignRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicDesigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicDesigns();
            return result;
        }
    }
    async getAllPublicDesignsByTitle(): Promise<Array<DesignRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicDesignsByTitle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicDesignsByTitle();
            return result;
        }
    }
    async getAllUserDesigns(): Promise<Array<DesignRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserDesigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserDesigns();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiKeys();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesign(arg0: string): Promise<DesignRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesign(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesign(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMembers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembers();
            return result;
        }
    }
    async getUserDesigns(arg0: Principal): Promise<Array<DesignRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDesigns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDesigns(arg0);
            return result;
        }
    }
    async inviteTeamMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteTeamMember(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isSubscriptionActive(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSubscriptionActive();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSubscriptionActive();
            return result;
        }
    }
    async removeTeamMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTeamMember(arg0);
            return result;
        }
    }
    async saveDesign(arg0: DesignRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDesign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDesign(arg0);
            return result;
        }
    }
    async saveUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(to_candid_UserProfile_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setDesignPublicStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDesignPublicStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDesignPublicStatus(arg0, arg1);
            return result;
        }
    }
    async setSubscriptionStatus(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSubscriptionStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSubscriptionStatus(arg0, arg1);
            return result;
        }
    }
    async setSubscriptionTier(arg0: Principal, arg1: SubscriptionTier): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSubscriptionTier(arg0, to_candid_SubscriptionTier_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSubscriptionTier(arg0, to_candid_SubscriptionTier_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async subscriptionTier(): Promise<SubscriptionTier> {
        if (this.processError) {
            try {
                const result = await this.actor.subscriptionTier();
                return from_candid_SubscriptionTier_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscriptionTier();
            return from_candid_SubscriptionTier_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_SubscriptionTier_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DesignRecord]): DesignRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    credits: bigint;
    username: string;
    apiKeys: Array<string>;
    subscriptionTier: _SubscriptionTier;
    teamMembers: Array<Principal>;
    subscriptionActive: boolean;
}): {
    principal: Principal;
    credits: bigint;
    username: string;
    apiKeys: Array<string>;
    subscriptionTier: SubscriptionTier;
    teamMembers: Array<Principal>;
    subscriptionActive: boolean;
} {
    return {
        principal: value.principal,
        credits: value.credits,
        username: value.username,
        apiKeys: value.apiKeys,
        subscriptionTier: from_candid_SubscriptionTier_n6(_uploadFile, _downloadFile, value.subscriptionTier),
        teamMembers: value.teamMembers,
        subscriptionActive: value.subscriptionActive
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    big: null;
} | {
    premium: null;
} | {
    none: null;
} | {
    extreme: null;
} | {
    small: null;
} | {
    medium: null;
}): SubscriptionTier {
    return "big" in value ? SubscriptionTier.big : "premium" in value ? SubscriptionTier.premium : "none" in value ? SubscriptionTier.none : "extreme" in value ? SubscriptionTier.extreme : "small" in value ? SubscriptionTier.small : "medium" in value ? SubscriptionTier.medium : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n4(_uploadFile, _downloadFile, x));
}
function to_candid_SubscriptionTier_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    credits: bigint;
    username: string;
    apiKeys: Array<string>;
    subscriptionTier: SubscriptionTier;
    teamMembers: Array<Principal>;
    subscriptionActive: boolean;
}): {
    principal: Principal;
    credits: bigint;
    username: string;
    apiKeys: Array<string>;
    subscriptionTier: _SubscriptionTier;
    teamMembers: Array<Principal>;
    subscriptionActive: boolean;
} {
    return {
        principal: value.principal,
        credits: value.credits,
        username: value.username,
        apiKeys: value.apiKeys,
        subscriptionTier: to_candid_SubscriptionTier_n13(_uploadFile, _downloadFile, value.subscriptionTier),
        teamMembers: value.teamMembers,
        subscriptionActive: value.subscriptionActive
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    big: null;
} | {
    premium: null;
} | {
    none: null;
} | {
    extreme: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == SubscriptionTier.big ? {
        big: null
    } : value == SubscriptionTier.premium ? {
        premium: null
    } : value == SubscriptionTier.none ? {
        none: null
    } : value == SubscriptionTier.extreme ? {
        extreme: null
    } : value == SubscriptionTier.small ? {
        small: null
    } : value == SubscriptionTier.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
